# Generated by Django 2.2 on 2019-04-24 02:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField(verbose_name='章节序号')),
                ('chapter_name', models.CharField(max_length=50, verbose_name='章节标题')),
                ('chapter_intro', models.CharField(max_length=300, verbose_name='章节简介')),
                ('chapter_date', models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 23, 3, 184365), verbose_name='发布时间')),
                ('chapter_extra_data', models.CharField(max_length=500, verbose_name='其他内容')),
            ],
            options={
                'verbose_name': '章节信息',
                'verbose_name_plural': '章节信息',
                'ordering': ('chapter_num',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, verbose_name='课程名')),
                ('lesson_intro', models.CharField(max_length=300, verbose_name='课程简介')),
                ('lesson_chapter', models.CharField(max_length=300, verbose_name='章节')),
                ('lesson_date', models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 23, 3, 184365), verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '课程信息',
                'verbose_name_plural': '课程信息',
            },
        ),
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=50, verbose_name='资料名')),
                ('data_path', models.CharField(max_length=500, verbose_name='资料下载路径')),
                ('data_is_free', models.SmallIntegerField(default=0, verbose_name='是否免费')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程号')),
            ],
            options={
                'verbose_name': '课程资料',
                'verbose_name_plural': '课程资料',
            },
        ),
        migrations.CreateModel(
            name='CourseBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_num', models.IntegerField(verbose_name='块序号')),
                ('block_word', models.TextField(blank=True, null=True, verbose_name='文字说明')),
                ('block_video', models.CharField(blank=True, max_length=300, null=True, verbose_name='视频说明')),
                ('block_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='图片说明')),
                ('block_code', models.TextField(blank=True, null=True, verbose_name='代码说明')),
                ('block_experiment', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='代码版')),
                ('chapter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Chapter', verbose_name='章节号')),
                ('lesson_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程号')),
            ],
            options={
                'verbose_name': '课程模块',
                'verbose_name_plural': '课程模块',
                'ordering': ('lesson_id', 'chapter_id', 'block_num'),
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lesson', verbose_name='课程号'),
        ),
    ]
