# Generated by Django 2.2.1 on 2019-05-03 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190430_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
