# Generated by Django 2.2.1 on 2019-05-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_chapter_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='chapter_num',
            field=models.IntegerField(default=1, verbose_name='章节数目'),
        ),
    ]
