# Generated by Django 2.2.1 on 2019-05-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190503_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseblock',
            name='block_img',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='图片说明'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_img',
            field=models.TextField(blank=True, null=True, verbose_name='课程封面'),
        ),
    ]
