# Generated by Django 2.2 on 2019-04-26 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190426_1012'),
        ('operations', '0003_auto_20190424_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 10, 11, 31, 878440), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='history_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 10, 11, 31, 862843), verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 10, 11, 31, 878440), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='usernotebook',
            name='notebook_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 10, 11, 31, 878440), verbose_name='发布时间'),
        ),
        migrations.CreateModel(
            name='UserProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.CharField(max_length=50, verbose_name='问题标题')),
                ('problem_content', models.CharField(max_length=500, verbose_name='问题描述')),
                ('problem_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='问题图片')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile', verbose_name='用户号')),
            ],
            options={
                'verbose_name': '用户提问',
                'verbose_name_plural': '用户提问',
            },
        ),
    ]
