# Generated by Django 2.2 on 2019-04-29 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20190426_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='comment_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operations.UserProblem', verbose_name='评论问题'),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='problem_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 1, 14, 843825), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 1, 14, 843825), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='history_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 1, 14, 843825), verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 1, 14, 843825), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='usernotebook',
            name='notebook_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 15, 1, 14, 843825), verbose_name='发布时间'),
        ),
    ]
