# Generated by Django 2.2.1 on 2019-05-03 09:31

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20190429_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 9, 31, 20, 399703), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='history_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 9, 31, 20, 394700), verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 9, 31, 20, 396701), verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='usernotebook',
            name='notebook_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 9, 31, 20, 401706), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userproblem',
            name='problem_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
