# Generated by Django 2.2.1 on 2019-05-03 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_auto_20190503_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='history_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='message_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='usernotebook',
            name='notebook_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
