# Generated by Django 2.2.1 on 2019-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0008_auto_20190503_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='message_hasread',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
    ]
