# Generated by Django 2.2.1 on 2019-05-16 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_auto_20190513_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproblem',
            name='problem_img',
        ),
        migrations.AddField(
            model_name='userproblem',
            name='problem_img1',
            field=models.TextField(blank=True, null=True, verbose_name='问题图片1'),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='problem_img2',
            field=models.TextField(blank=True, null=True, verbose_name='问题图片2'),
        ),
        migrations.AddField(
            model_name='userproblem',
            name='problem_img3',
            field=models.TextField(blank=True, null=True, verbose_name='问题图片3'),
        ),
    ]
