# Generated by Django 2.2 on 2019-04-24 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(max_length=20, unique=True, verbose_name='api函数/定义名')),
                ('api_intro', models.TextField(verbose_name='api解释')),
                ('api_code', models.CharField(max_length=1000, verbose_name='实现代码')),
            ],
            options={
                'verbose_name': 'api检索',
                'verbose_name_plural': 'api检索',
                'ordering': ('api_name',),
            },
        ),
        migrations.CreateModel(
            name='Global',
            fields=[
                ('global_account', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='管理员账号')),
                ('global_password', models.CharField(max_length=32, verbose_name='管理员密码')),
                ('global_download_cost', models.IntegerField(verbose_name='下载资料所需积分')),
                ('global_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='其他')),
            ],
            options={
                'verbose_name': '全局数据',
                'verbose_name_plural': '全局数据',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_content', models.TextField(verbose_name='新闻内容')),
                ('news_date', models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 27, 27, 302167), verbose_name='日期')),
                ('news_extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='其他')),
            ],
            options={
                'verbose_name': '新闻资讯',
                'verbose_name_plural': '新闻资讯',
                'ordering': ('news_date',),
            },
        ),
        migrations.CreateModel(
            name='TermSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=20, unique=True, verbose_name='术语名')),
                ('term_intro', models.TextField(verbose_name='术语解释')),
                ('term_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='解释图')),
            ],
            options={
                'verbose_name': '术语检索',
                'verbose_name_plural': '术语检索',
                'ordering': ('term_name',),
            },
        ),
    ]
