# Generated by Django 2.2 on 2019-04-24 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 35, 8, 239261), verbose_name='日期'),
        ),
    ]
