# Generated by Django 2.2 on 2019-04-29 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20190424_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='新闻图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 9, 4, 55, 730021), verbose_name='日期'),
        ),
    ]
