# Generated by Django 2.2 on 2019-04-30 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_auto_20190429_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AnswerQuestion_title', models.CharField(max_length=50, verbose_name='问题标题')),
                ('AnswerQuestion_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='回答图片')),
                ('AnswerQuestion_content', models.TextField(verbose_name='回答内容')),
                ('AnswerQuestion_date', models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 10, 26, 704983), verbose_name='发布时间')),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 10, 26, 704983), verbose_name='日期'),
        ),
    ]
