# Generated by Django 2.2 on 2019-04-30 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_auto_20190430_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'verbose_name': '官方答疑', 'verbose_name_plural': '官方答疑'},
        ),
        migrations.RemoveField(
            model_name='answerquestion',
            name='AnswerQuestion_content',
        ),
        migrations.RemoveField(
            model_name='answerquestion',
            name='AnswerQuestion_date',
        ),
        migrations.RemoveField(
            model_name='answerquestion',
            name='AnswerQuestion_img',
        ),
        migrations.RemoveField(
            model_name='answerquestion',
            name='AnswerQuestion_title',
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_content',
            field=models.TextField(default='5月4日起每周六晚20：30 ', verbose_name='答疑内容'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 23, 51, 108513), verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='答疑图片'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='answer_title',
            field=models.CharField(default='《青春环游记》播出时间？', max_length=50, verbose_name='答疑标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 23, 51, 108513), verbose_name='日期'),
        ),
    ]
