# Generated by Django 2.2 on 2019-04-30 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_auto_20190430_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_content',
            field=models.TextField(verbose_name='答疑内容'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 26, 6, 957202), verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_title',
            field=models.CharField(max_length=50, verbose_name='答疑标题'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 30, 10, 26, 6, 957202), verbose_name='日期'),
        ),
    ]
