# Generated by Django 2.2.1 on 2019-05-03 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0008_auto_20190503_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间'),
        ),
    ]
