# Generated by Django 2.2.1 on 2019-05-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0009_auto_20190503_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerquestion',
            name='answer_img',
            field=models.TextField(blank=True, null=True, verbose_name='答疑图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_img',
            field=models.TextField(blank=True, null=True, verbose_name='新闻图片'),
        ),
    ]
