# Generated by Django 2.2.1 on 2019-05-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0010_auto_20190513_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=20, verbose_name='资源名')),
                ('resource_type', models.IntegerField(verbose_name='资源类型')),
                ('resource_link', models.CharField(max_length=400, verbose_name='下载链接')),
            ],
            options={
                'verbose_name': '资源下载',
                'verbose_name_plural': '资源下载',
            },
        ),
    ]
