# Generated by Django 2.2.1 on 2019-05-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0011_resourcedownload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcedownload',
            options={'ordering': ('resource_type',), 'verbose_name': '资源下载', 'verbose_name_plural': '资源下载'},
        ),
    ]
