# Generated by Django 2.2.1 on 2019-05-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0012_auto_20190515_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_link',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='新闻链接'),
        ),
    ]
