# Generated by Django 2.2 on 2019-04-24 02:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('user_account', models.IntegerField(verbose_name='账号')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 14, 34, 481750))),
            ],
            options={
                'verbose_name': '手机验证码',
                'verbose_name_plural': '手机验证码',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.IntegerField(unique=True, verbose_name='账号')),
                ('user_password', models.CharField(max_length=32, verbose_name='密码')),
                ('user_score', models.IntegerField(default=0, verbose_name='积分')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
