# Generated by Django 2.2 on 2019-04-24 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190424_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 57, 19, 480394)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_account',
            field=models.CharField(max_length=11, unique=True, verbose_name='账号'),
        ),
    ]
