# Generated by Django 2.2 on 2019-04-24 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190424_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 10, 58, 21, 151986)),
        ),
        migrations.AlterField(
            model_name='telverifyrecord',
            name='user_account',
            field=models.CharField(max_length=11, verbose_name='账号'),
        ),
    ]
