# Generated by Django 2.2 on 2019-04-24 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190424_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 11, 10, 2, 414879)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_account',
            field=models.CharField(max_length=12, unique=True, verbose_name='账号'),
        ),
    ]
