# Generated by Django 2.2 on 2019-04-24 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190424_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 24, 11, 13, 30, 521772)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_account',
            field=models.CharField(max_length=11, unique=True, verbose_name='账号'),
        ),
    ]
