# Generated by Django 2.2 on 2019-04-26 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190424_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_accout', models.CharField(max_length=11, verbose_name='账号')),
                ('head_img', models.CharField(blank=True, max_length=300, null=True, verbose_name='头像')),
            ],
            options={
                'verbose_name': '头像',
                'verbose_name_plural': '头像',
            },
        ),
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 9, 52, 12, 340764)),
        ),
    ]
