# Generated by Django 2.2 on 2019-04-26 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190426_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userphoto',
            old_name='user_accout',
            new_name='user_account',
        ),
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 26, 10, 23, 5, 117424)),
        ),
    ]
