# Generated by Django 2.2 on 2019-04-27 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190426_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(default='无昵称', max_length=20, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 15, 57, 57, 591224)),
        ),
    ]
