# Generated by Django 2.2 on 2019-04-27 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190427_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 27, 16, 7, 23, 440)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_nickname',
            field=models.CharField(max_length=20, unique=True, verbose_name='昵称'),
        ),
    ]
