# Generated by Django 2.2.1 on 2019-05-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190502_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 10, 5, 39, 134784)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='头像'),
        ),
    ]
