# Generated by Django 2.2.1 on 2019-05-03 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20190502_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telverifyrecord',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='头像'),
        ),
    ]
