# Generated by Django 2.2.1 on 2019-05-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20190503_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_img',
            field=models.TextField(blank=True, null=True, verbose_name='头像'),
        ),
    ]
